# kind.yaml
# This file defines the configuration for your Kind Kubernetes cluster.
# It specifies a single control-plane node and maps host port 30000
# to the container port 30000, allowing NodePort services to be
# externally accessible on your EC2 instance.

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # extraPortMappings allows you to expose ports from the Kind node container
  # to the host machine (your EC2 instance in this case).
  # This is crucial for NodePort services to be accessible from outside the EC2 instance.
  extraPortMappings:
  - containerPort: 30000 # The port inside the Kind node container where NodePort services will listen
    hostPort: 30000      # The port on the EC2 instance's public IP that will map to containerPort
    listenAddress: "0.0.0.0" # Listen on all network interfaces of the EC2 instance
    protocol: tcp

