apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 533267328640.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: yoyoyo
    - name: MYSQL_DATABASE
      value: employees
    - name: MYSQL_USER
      value: sql_user
    - name: MYSQL_PASSWORD
      value: yoyoyo
  imagePullSecrets:
  - name: regcred
